### ISSUE TITLE
Session 1 - Logic - HR Challenge

### ISSUE THREAD

**Issue by fcu423** [lucoch10/net-bootcamp#1]
Luis:

1. Para Mars Exploration no subiste la imagen pasando los tests de Hacker Rank. Revisando la lógica creo que fallaría. Podés analizar qué pasaría en caso de que la entrada sea: "SSSOOOSSSOOO"?

2. En la lógica de grading hay algunas cosas por corregir para que el código quede mejor:

- Las variables que están declaradas en la línea 32 - 33 - 40 serán creadas en cada iteración del for, con lo que estarás desperdiciando memoria. Es mejor si declaras las variables fuera del ciclo y las reutilizas adentro
- Línea 49 y 50: Es buena práctica en .NET siempre poner las llaves en cualquier cláusula que las lleve así el contenido de la cláusula sea de una sola línea. Esto mejora la legibilidad del código
- Es buena práctica siempre programar en un solo idioma, preferiblemente en inglés. Hay algunas variables en inglés y español.

👍

**Comment by lucoch10** [comment]
Si @fcu423 creo q puse en un trello que mi test case para Mars no había pasado pero estaba atrasado para el challenge dos, voy a ver si arreglo ese rapidito, para el punto 2 esta semana los corrijo :)

**Comment by lucoch10** [comment]
Hola @fcu423 ya arreglé todo y lo subí a Git con sus respectivos commit :)

**Comment by fcu423** [comment]
Correcciones revisadas
